sonar.projectKey=Space2Study-UA-4427-4288-01_Client-01
sonar.organization=space2study-ua-4427-4288-01

sonar.projectName=SpaceToStudy-Client

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.
sonar.exclusions=**/src/tests/**/*, **/build-story/*
sonar.coverage.exclusions=**/src/constants/*, **/src/tests/**/*, **/*.styles.ts

sonar.tests=./src/tests

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8
